swagger: "2.0"
info:
  description: Endpoint definitions for backend_main.py
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

#Global API Key Security
#security:
#  - APIKeyHeader: []

#Change definitions soon
# Paths supported by the server application

paths:
  /authenticate/default:
    post:
      operationId: endpoint_entry.user_authenticate_default
      tags:
        - sys_user
      summary: Authentication
      description: Authenticate user with username and password
      parameters:
        - name: auth_user_default
          in: body
          description: Data wrapper
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  username:
                    type: string
                    description: User username
                  password:
                    type: string
                    description: User password
                required:
                  - username
                  - password
            required:
              - data
      responses:
        200:
          description: Successful authentication
          schema:
            type: object
            properties:
              data:
                type: object

  /authenticate/google:
    post:
      operationId: endpoint_entry.user_authenticate_gmail
      tags:
        - sys_user
      summary: Authentication
      description: Authenticate user with google email
      parameters:
        - name: auth_user_gmail
          in: body
          description: Data wrapper
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  email:
                    type: string
                    description: User gmail
                required:
                 - email
            required:
             - data
      responses:
        200:
          description: Successful authentication
          schema:
            type: object
            properties:
              data:
                type: object

  /authenticate/facebook:
    post:
      operationId: endpoint_entry.user_authenticate_fb
      tags:
        - sys_user
      summary: Authentication
      description: Authenticate user with facebook email
      parameters:
        - name: auth_user_fb
          in: body
          description: Data wrapper
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  email:
                    type: string
                    description: User facebook email
                required:
                 - email
            required:
             - data    
      responses:
        200:
          description: Successful authentication
          schema:
            type: object
            properties:
              data:
                type: object

  /inventory:
    get:
      operationId: endpoint_entry.get_company_product
      description: Return all company products in the database
      responses:
        200:
          description: List of all company products 
          schema:
            type: object
            properties:
              data:
                type: array

  /orders/not_delivered:
    get:
      operationId: endpoint_entry.get_order_not_delivered
      description: Return all shop orders in the database that have completed = False
      responses:
        200:
          description: List of all shop orders that are not delivered 
          schema:
            type: object
            properties:
              data:
                type: array

  /orders/today:
    get:
      operationId: endpoint_entry.get_order_today
      description: Return all shop orders that are set to be delivered today
      responses:
        200:
          description: List of all shop orders that are set to be delivered today 
          schema:
            type: object
            properties:
              data:
                type: array

  /shops/all:
    get:
      operationId: endpoint_entry.get_all_shops
      description: Return all shops in database
      responses:
        200:
          description: List of all shops
          schema:
            type: object
            properties:
              data:
                type: array

  /zones/all:
    get:
      operationId: endpoint_entry.get_all_zones
      description: Return all zones in database
      responses:
        200:
          description: List of all zones 
          schema:
            type: object
            properties:
              data:
                type: array

  /shop_categories/all:
    get:
      operationId: endpoint_entry.get_all_shop_category
      description: Return all shop categories in database
      responses:
        200:
          description: List of all shop categories
          schema:
            type: object
            properties:
              data:
                type: array

  /create/shop:
    post:
      operationId: endpoint_entry.shop_create
      description: Create a new shop with JSON data
      parameters:
        - name: new_shop
          in: body
          description: Data wrapper
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  name:
                    type: string
                    description: Shop name
                  email:
                    type: string
                    x-nullable: true
                    description: Shop email
                  image_url:
                    type: string
                    description: Shop image url
                  phone_number:
                    type: string
                    x-nullable: true
                    description: Shop phone number
                  category:
                    type: integer
                    x-nullable: true
                    description: Shop category
                  zones:
                    type: array
                    description: Shop zones
                    properties:
                      id:
                        type: integer
                        description: Zone database id
                    required:
                     - id
                  street:
                    type: string
                    description: Shop street address
                  city:
                    type: string
                    description: Shop city address
                  providence:
                    type: string
                    description: Shop providence
                  zip_4:
                    type: string
                    description: Shop zip_4 code
                required:
                 - name
                 - email
                 - image_url
                 - phone_number
                 - category
                 - street
                 - zones
                 - city
                 - providence
                 - zip_4
            required:
             - data
      responses:
        200:
          description: Return data for newly created shop 
          schema:
            type: object
            properties:
              data:
                type: object

  /create/zone:
    post:
      operationId: endpoint_entry.zone_create
      description: Create a new zone with JSON data
      parameters:
        - name: new_zone
          in: body
          description: Data wrapper
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  name:
                    type: string
                    description: Zone name
                required:
                 - name
            required:
             - data
      responses:
        200:
          description: Return data for newly created zone 
          schema:
            type: object
            properties:
              data:
                type: object

  /create/shop_category:
    post:
      operationId: endpoint_entry.shop_category_create
      description: Create a new shop category with JSON data
      parameters:
        - name: new_shop_category
          in: body
          description: Data wrapper
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  type:
                    type: string
                    description: Shop category type
                required:
                 - type
            required:
             - data
      responses:
        200:
          description: Return data for newly created shop category
          schema:
            type: object
            properties:
              data:
                type: object

  /create/shop_order:
    post:
      operationId: endpoint_entry.shop_order_create
      description: Create a new shop order with JSON data
      parameters:
        - name: new_shop_order
          in: body
          description: Data wrapper
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  shop_id:
                    type: integer
                    description: Shop database id that the order is placed for
                  price_paid:
                    type: boolean
                    description: True if the order was paid for when the order was taken
                  deliver_days_from_today:
                    type: integer
                    description: Days from today that the order will be delivered
                  memo:
                    type: string
                    description: Shop order memo
                  order_taker_id:
                    type: integer
                    description: Order Taker database id
                  order_items:
                    type: array
                    description: Array of items ordered by the shop
                    items:
                      properties:
                        id:
                          type: integer
                          description: Company product database id
                        quantity_units:
                          type: integer
                          description: Ammount of company product ordered
                      required:
                       - id
                       - quantity_units
                required:
                 - shop_id
                 - price_paid
                 - deliver_days_from_today
                 - memo
                 - order_taker_id
                 - order_items
            required:
             - data
      responses:
        200:
          description: Return data for newly created shop order 
          schema:
            type: object
            properties:
              data:
                type: object

  /deliver/shop_order:
    post:
      operationId: endpoint_entry.shop_order_update
      description: Update a shop order as delivered with JSON data
      parameters:
        - name: update_shop_order
          in: body
          description: User to create
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                description: Email of user to create
                properties:
                  shop_order_id:
                    type: integer
                    description: Email of user to create
                  order_fulfiller_id:
                    type: integer
                    description: Email of user to create
                required:
                 - shop_order_id
                 - order_fulfiller_id
            required:
             - data
      responses:
        200:
          description: Successful read user list 
          schema:
            type: object
            properties:
              data:
                type: object

  /goal/order_taker:
    post:
      operationId: endpoint_entry.goal_order_taker
      description: Get the goal data for a order taker for this month with JSON data
      parameters:
        - name: order_taker_info
          in: body
          description: order_taker to get data for
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                description: Data wrapper
                properties:
                  order_taker_id:
                    type: integer
                    description: Database id of order taker
                required:
                 - order_taker_id
            required:
             - data
      responses:
        200:
          description: goal_order_taker data 
          schema:
            type: object
            properties:
              data:
                type: object

  /goal/order_taker/new:
    post:
      operationId: endpoint_entry.goal_order_taker_new
      description: Create goal data for a order taker for this month with JSON data
      parameters:
        - name: goal_info
          in: body
          description: order_taker to get data for
          required: True
          schema:
            type: object
            properties:
              data:
                type: object
                description: Data wrapper
                properties:
                  order_taker_id:
                    type: integer
                    description: Database id of order taker
                  goal_total:
                    type: number
                    description: Money value of goal
                required:
                 - order_taker_id
                 - goal_total
            required:
             - data
      responses:
        200:
          description: goal_order_taker data 
          schema:
            type: object
            properties:
              data:
                type: object

securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key
    x-apikeyInfoFunc: api.basic_auth
