# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        astroid==2.3.0
        attrs==20.3.0
        awscli==1.18.165
        backcall==0.2.0
        botocore==1.19.5
        certifi==2020.6.20
        chardet==3.0.4
        click==7.1.2
        clickclick==20.10.2
        colorama==0.4.3
        connexion==2.7.0
        decorator==4.4.2
        Django==2.0.2
        dnspython==1.16.0
        docutils==0.15.2
        eventlet==0.29.1
        Flask==1.1.2
        Flask-Cors==3.0.9
        Flask-SocketIO==4.3.1
        Flask-SQLAlchemy==2.1
        git-remote-codecommit==1.15.1
        greenlet==0.4.17
        idna==2.10
        ikp3db==1.4.1
        importlib-metadata==2.0.0
        inflection==0.5.1
        ipython==7.16.1
        ipython-genutils==0.2.0
        isort==4.3.21
        itsdangerous==1.1.0
        jedi==0.11.1
        Jinja2==2.11.2
        jmespath==0.10.0
        jsonschema==3.2.0
        lazy-object-proxy==1.5.1
        MarkupSafe==1.1.1
        mccabe==0.6.1
        openapi-spec-validator==0.2.9
        parso==0.1.1
        pbr==5.5.1
        pexpect==4.8.0
        pickleshare==0.7.5
        prompt-toolkit==3.0.8
        psycopg2-binary==2.8.6
        ptyprocess==0.6.0
        pyasn1==0.4.8
        Pygments==2.7.2
        pylint==2.4.4
        pylint-django==2.3.0
        pylint-flask==0.6
        pylint-plugin-utils==0.6
        pyrsistent==0.17.3
        python-dateutil==2.8.1
        python-dotenv==0.15.0
        python-engineio==3.13.2
        python-socketio==4.6.0
        pytz==2020.1
        PyYAML==5.3.1
        requests==2.24.0
        rsa==4.5
        s3transfer==0.3.3
        six==1.15.0
        SQLAlchemy==1.3.20
        stevedore==3.2.2
        swagger-ui-bundle==0.0.8
        traitlets==4.3.3
        typed-ast==1.2.0
        urllib3==1.25.11
        virtualenv==16.2.0
        virtualenv-clone==0.5.4
        virtualenvwrapper==4.8.4
        wcwidth==0.2.5
        Werkzeug==1.0.1
        wrapt==1.12.1
        zipp==3.4.0
    - name: Testing test_sql_tables.py
      run: |
        sudo python backend/unit_tests/test_sql_tables.py
    - name: Testing test_endpoint_logic.py
      run: |
        sudo python backend/unit_tests/test_endpoint_logic.py
